#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Information that specifies the type of case.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum incident_casetypecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Repair = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Complaint = 2,
}

/// <summary>
/// Response level for the case. The response level corresponds to the level of service specified in the contract.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum incident_contractservicelevelcode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Gold = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Silver = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Bronze = 3,
}

/// <summary>
/// Customer's level of satisfaction with the resolution of the case.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum incident_customersatisfactioncode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	VerySatisfied = 5,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Satisfied = 4,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Neutral = 3,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Dissatisfied = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	VeryDissatisfied = 1,
}

/// <summary>
/// First Response SLA Status
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum incident_firstresponseslastatus
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	InProgress = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	NearingNoncompliance = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Succeeded = 3,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Noncompliant = 4,
}

/// <summary>
/// Stage of the resolution process for the case.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum incident_incidentstagecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	DefaultValue = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum msdyn_case_msdyn_casesentiment
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	NA = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Verynegative = 7,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Negative = 8,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Slightlynegative = 9,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Neutral = 10,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Slightlypositive = 11,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Positive = 12,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Verypositive = 13,
}

/// <summary>
/// Priority of the case.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum incident_prioritycode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	High = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Normal = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Low = 3,
}

/// <summary>
/// ResolveBy SLA Status
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum incident_resolvebyslastatus
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	InProgress = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	NearingNoncompliance = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Succeeded = 3,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Noncompliant = 4,
}

/// <summary>
/// Severity of the case.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum incident_severitycode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	DefaultValue = 1,
}

/// <summary>
/// Status of the case.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum incident_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Resolved = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Cancelled = 2,
}

/// <summary>
/// Reason for the status of the case.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum incident_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	New = 563910009,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	ProblemSolved = 5,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	InformationProvided = 1000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Cancelled = 6,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Merged = 2000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	InProgress = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	OnHold = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	WaitingforDetails = 3,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Researching = 4,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	OnholdCustomer = 563910001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	FirstAidgiven = 563910002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	OnholdInternal = 563910003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	WOInProgress = 563910004,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	FirstAidSuccessful = 563910005,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	WOCompleted = 563910006,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	WOCancellation = 563910007,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	ConverttoSales = 563910008,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Cancellationduetocustomercall = 563910010,
}

/// <summary>
/// Service request case associated with a contract.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("incident")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class Incident : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
		/// <summary>
		/// Available fields, a the time of codegen, for the incident entity
		/// </summary>
		public partial class Fields
		{
			public const string AccountId = "accountid";
			public const string ActivitiesComplete = "activitiescomplete";
			public const string ActualServiceUnits = "actualserviceunits";
			public const string BilledServiceUnits = "billedserviceunits";
			public const string BlockedProfile = "blockedprofile";
			public const string bshcs_caller = "bshcs_caller";
			public const string bshcs_customerassetid = "bshcs_customerassetid";
			public const string bshcs_duedate = "bshcs_duedate";
			public const string bshcs_firstaidautoclose = "bshcs_firstaidautoclose";
			public const string bshcs_firstaidprovidedon = "bshcs_firstaidprovidedon";
			public const string bshcs_onsitecontactemail = "bshcs_onsitecontactemail";
			public const string bshcs_onsitecontactname = "bshcs_onsitecontactname";
			public const string bshcs_onsitecontactphone = "bshcs_onsitecontactphone";
			public const string bshcs_qt_json = "bshcs_qt_json";
			public const string bshcs_repairbatchcase = "bshcs_repairbatchcase";
			public const string caseage = "caseage";
			public const string CaseOriginCode = "caseorigincode";
			public const string CaseTypeCode = "casetypecode";
			public const string CheckEmail = "checkemail";
			public const string ContactId = "contactid";
			public const string ContractDetailId = "contractdetailid";
			public const string ContractId = "contractid";
			public const string ContractServiceLevelCode = "contractservicelevelcode";
			public const string CreatedBy = "createdby";
			public const string CreatedByExternalParty = "createdbyexternalparty";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CustomerContacted = "customercontacted";
			public const string CustomerId = "customerid";
			public const string CustomerSatisfactionCode = "customersatisfactioncode";
			public const string deactivatedon = "deactivatedon";
			public const string DecrementEntitlementTerm = "decremententitlementterm";
			public const string Description = "description";
			public const string EmailAddress = "emailaddress";
			public const string EntitlementId = "entitlementid";
			public const string EntityImage = "entityimage";
			public const string EntityImage_Timestamp = "entityimage_timestamp";
			public const string EntityImage_URL = "entityimage_url";
			public const string EntityImageId = "entityimageid";
			public const string EscalatedOn = "escalatedon";
			public const string ExchangeRate = "exchangerate";
			public const string ExistingCase = "existingcase";
			public const string FirstResponseByKPIId = "firstresponsebykpiid";
			public const string FirstResponseSent = "firstresponsesent";
			public const string FirstResponseSLAStatus = "firstresponseslastatus";
			public const string FollowupBy = "followupby";
			public const string FollowUpTaskCreated = "followuptaskcreated";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string IncidentId = "incidentid";
			public const string Id = "incidentid";
			public const string IncidentStageCode = "incidentstagecode";
			public const string InfluenceScore = "influencescore";
			public const string IsDecrementing = "isdecrementing";
			public const string IsEscalated = "isescalated";
			public const string KbArticleId = "kbarticleid";
			public const string lastinteraction = "lastinteraction";
			public const string LastOnHoldTime = "lastonholdtime";
			public const string MasterId = "masterid";
			public const string Merged = "merged";
			public const string MessageTypeCode = "messagetypecode";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByExternalParty = "modifiedbyexternalparty";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string msdyn_aiagentstatus = "msdyn_aiagentstatus";
			public const string msdyn_casesentiment = "msdyn_casesentiment";
			public const string msdyn_CaseSurveyInviteUrl = "msdyn_casesurveyinviteurl";
			public const string msdyn_copilotengaged = "msdyn_copilotengaged";
			public const string msdyn_FunctionalLocation = "msdyn_functionallocation";
			public const string msdyn_IncidentType = "msdyn_incidenttype";
			public const string msdyn_iotalert = "msdyn_iotalert";
			public const string msdyn_precreateattachmentsid = "msdyn_precreateattachmentsid";
			public const string msdyn_precreatenotesid = "msdyn_precreatenotesid";
			public const string nextsla = "nextsla";
			public const string NumberOfChildIncidents = "numberofchildincidents";
			public const string OnHoldTime = "onholdtime";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string ParentCaseId = "parentcaseid";
			public const string PrimaryContactId = "primarycontactid";
			public const string PriorityCode = "prioritycode";
			public const string ProcessId = "processid";
			public const string ProductId = "productid";
			public const string ProductSerialNumber = "productserialnumber";
			public const string ResolveBy = "resolveby";
			public const string ResolveByKPIId = "resolvebykpiid";
			public const string ResolveBySLAStatus = "resolvebyslastatus";
			public const string ResponseBy = "responseby";
			public const string ResponsibleContactId = "responsiblecontactid";
			public const string RouteCase = "routecase";
			public const string SentimentValue = "sentimentvalue";
			public const string ServiceStage = "servicestage";
			public const string SeverityCode = "severitycode";
			public const string SLAId = "slaid";
			public const string SLAInvokedId = "slainvokedid";
			public const string SocialProfileId = "socialprofileid";
			public const string StageId = "stageid";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string SubjectId = "subjectid";
			public const string TicketNumber = "ticketnumber";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string Title = "title";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string TraversedPath = "traversedpath";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string Referencedincident_existingcase = "Referencedincident_existingcase";
			public const string Referencedincident_master_incident = "Referencedincident_master_incident";
			public const string Referencedincident_parent_incident = "Referencedincident_parent_incident";
			public const string bshcs_incident_bshcs_billingfunctionallocation = "bshcs_incident_bshcs_billingfunctionallocation";
			public const string Referencingincident_existingcase = "incident_existingcase";
			public const string Referencingincident_master_incident = "incident_master_incident";
			public const string Referencingincident_parent_incident = "incident_parent_incident";
		}
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public Incident() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "incident";
	
	public const string EntityLogicalCollectionName = "incidents";
	
	public const string EntitySetName = "incidents";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Unique identifier of the account with which the case is associated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("accountid")]
	public Microsoft.Xrm.Sdk.EntityReference AccountId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("accountid");
		}
	}
	
	/// <summary>
	/// This attribute is used for Sample Service Business Processes.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("activitiescomplete")]
	public System.Nullable<bool> ActivitiesComplete
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("activitiescomplete");
		}
		set
		{
			this.OnPropertyChanging("ActivitiesComplete");
			this.SetAttributeValue("activitiescomplete", value);
			this.OnPropertyChanged("ActivitiesComplete");
		}
	}
	
	/// <summary>
	/// Type the number of service units that were actually required to resolve the case.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("actualserviceunits")]
	public System.Nullable<int> ActualServiceUnits
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("actualserviceunits");
		}
		set
		{
			this.OnPropertyChanging("ActualServiceUnits");
			this.SetAttributeValue("actualserviceunits", value);
			this.OnPropertyChanged("ActualServiceUnits");
		}
	}
	
	/// <summary>
	/// Type the number of service units that were billed to the customer for the case.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billedserviceunits")]
	public System.Nullable<int> BilledServiceUnits
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("billedserviceunits");
		}
		set
		{
			this.OnPropertyChanging("BilledServiceUnits");
			this.SetAttributeValue("billedserviceunits", value);
			this.OnPropertyChanged("BilledServiceUnits");
		}
	}
	
	/// <summary>
	/// Details whether the profile is blocked or not.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("blockedprofile")]
	public System.Nullable<bool> BlockedProfile
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("blockedprofile");
		}
		set
		{
			this.OnPropertyChanging("BlockedProfile");
			this.SetAttributeValue("blockedprofile", value);
			this.OnPropertyChanged("BlockedProfile");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_caller")]
	public Microsoft.Xrm.Sdk.EntityReference bshcs_caller
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bshcs_caller");
		}
		set
		{
			this.OnPropertyChanging("bshcs_caller");
			this.SetAttributeValue("bshcs_caller", value);
			this.OnPropertyChanged("bshcs_caller");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_customerassetid")]
	public Microsoft.Xrm.Sdk.EntityReference bshcs_customerassetid
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bshcs_customerassetid");
		}
		set
		{
			this.OnPropertyChanging("bshcs_customerassetid");
			this.SetAttributeValue("bshcs_customerassetid", value);
			this.OnPropertyChanged("bshcs_customerassetid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_duedate")]
	public System.Nullable<System.DateTime> bshcs_duedate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("bshcs_duedate");
		}
		set
		{
			this.OnPropertyChanging("bshcs_duedate");
			this.SetAttributeValue("bshcs_duedate", value);
			this.OnPropertyChanged("bshcs_duedate");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_firstaidautoclose")]
	public System.Nullable<bool> bshcs_firstaidautoclose
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("bshcs_firstaidautoclose");
		}
		set
		{
			this.OnPropertyChanging("bshcs_firstaidautoclose");
			this.SetAttributeValue("bshcs_firstaidautoclose", value);
			this.OnPropertyChanged("bshcs_firstaidautoclose");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_firstaidprovidedon")]
	public System.Nullable<System.DateTime> bshcs_firstaidprovidedon
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("bshcs_firstaidprovidedon");
		}
		set
		{
			this.OnPropertyChanging("bshcs_firstaidprovidedon");
			this.SetAttributeValue("bshcs_firstaidprovidedon", value);
			this.OnPropertyChanged("bshcs_firstaidprovidedon");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_onsitecontactemail")]
	public string bshcs_onsitecontactemail
	{
		get
		{
			return this.GetAttributeValue<string>("bshcs_onsitecontactemail");
		}
		set
		{
			this.OnPropertyChanging("bshcs_onsitecontactemail");
			this.SetAttributeValue("bshcs_onsitecontactemail", value);
			this.OnPropertyChanged("bshcs_onsitecontactemail");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_onsitecontactname")]
	public string bshcs_onsitecontactname
	{
		get
		{
			return this.GetAttributeValue<string>("bshcs_onsitecontactname");
		}
		set
		{
			this.OnPropertyChanging("bshcs_onsitecontactname");
			this.SetAttributeValue("bshcs_onsitecontactname", value);
			this.OnPropertyChanged("bshcs_onsitecontactname");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_onsitecontactphone")]
	public string bshcs_onsitecontactphone
	{
		get
		{
			return this.GetAttributeValue<string>("bshcs_onsitecontactphone");
		}
		set
		{
			this.OnPropertyChanging("bshcs_onsitecontactphone");
			this.SetAttributeValue("bshcs_onsitecontactphone", value);
			this.OnPropertyChanged("bshcs_onsitecontactphone");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_qt_json")]
	public string bshcs_qt_json
	{
		get
		{
			return this.GetAttributeValue<string>("bshcs_qt_json");
		}
		set
		{
			this.OnPropertyChanging("bshcs_qt_json");
			this.SetAttributeValue("bshcs_qt_json", value);
			this.OnPropertyChanged("bshcs_qt_json");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_repairbatchcase")]
	public Microsoft.Xrm.Sdk.EntityReference bshcs_repairbatchcase
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bshcs_repairbatchcase");
		}
		set
		{
			this.OnPropertyChanging("bshcs_repairbatchcase");
			this.SetAttributeValue("bshcs_repairbatchcase", value);
			this.OnPropertyChanged("bshcs_repairbatchcase");
		}
	}
	
	/// <summary>
	/// Shows the duration for which the Case has been active for Active and Resolved Cases.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("caseage")]
	public string caseage
	{
		get
		{
			return this.GetAttributeValue<string>("caseage");
		}
	}
	
	/// <summary>
	/// Select how contact about the case was originated, such as email, phone, or web, for use in reporting and analysis.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("caseorigincode")]
	public virtual incident_caseorigincode? CaseOriginCode
	{
		get
		{
			return ((incident_caseorigincode?)(EntityOptionSetEnum.GetEnum(this, "caseorigincode")));
		}
		set
		{
			this.OnPropertyChanging("CaseOriginCode");
			this.SetAttributeValue("caseorigincode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("CaseOriginCode");
		}
	}
	
	/// <summary>
	/// Select the type of case to identify the incident for use in case routing and analysis.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("casetypecode")]
	public virtual incident_casetypecode? CaseTypeCode
	{
		get
		{
			return ((incident_casetypecode?)(EntityOptionSetEnum.GetEnum(this, "casetypecode")));
		}
		set
		{
			this.OnPropertyChanging("CaseTypeCode");
			this.SetAttributeValue("casetypecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("CaseTypeCode");
		}
	}
	
	/// <summary>
	/// This attribute is used for Sample Service Business Processes.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("checkemail")]
	public System.Nullable<bool> CheckEmail
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("checkemail");
		}
		set
		{
			this.OnPropertyChanging("CheckEmail");
			this.SetAttributeValue("checkemail", value);
			this.OnPropertyChanged("CheckEmail");
		}
	}
	
	/// <summary>
	/// Unique identifier of the contact associated with the case.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contactid")]
	public Microsoft.Xrm.Sdk.EntityReference ContactId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("contactid");
		}
	}
	
	/// <summary>
	/// Choose the contract line that the case should be logged under to make sure the customer is charged correctly.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contractdetailid")]
	public Microsoft.Xrm.Sdk.EntityReference ContractDetailId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("contractdetailid");
		}
		set
		{
			this.OnPropertyChanging("ContractDetailId");
			this.SetAttributeValue("contractdetailid", value);
			this.OnPropertyChanged("ContractDetailId");
		}
	}
	
	/// <summary>
	/// Choose the service contract that the case should be logged under to make sure the customer is eligible for support services.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contractid")]
	public Microsoft.Xrm.Sdk.EntityReference ContractId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("contractid");
		}
		set
		{
			this.OnPropertyChanging("ContractId");
			this.SetAttributeValue("contractid", value);
			this.OnPropertyChanged("ContractId");
		}
	}
	
	/// <summary>
	/// Select the service level for the case to make sure the case is handled correctly.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contractservicelevelcode")]
	public virtual incident_contractservicelevelcode? ContractServiceLevelCode
	{
		get
		{
			return ((incident_contractservicelevelcode?)(EntityOptionSetEnum.GetEnum(this, "contractservicelevelcode")));
		}
		set
		{
			this.OnPropertyChanging("ContractServiceLevelCode");
			this.SetAttributeValue("contractservicelevelcode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("ContractServiceLevelCode");
		}
	}
	
	/// <summary>
	/// Shows who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Shows the external party who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyexternalparty")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedByExternalParty
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdbyexternalparty");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Shows who created the record on behalf of another user.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Tells whether customer service representative has contacted the customer or not.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customercontacted")]
	public System.Nullable<bool> CustomerContacted
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("customercontacted");
		}
		set
		{
			this.OnPropertyChanging("CustomerContacted");
			this.SetAttributeValue("customercontacted", value);
			this.OnPropertyChanged("CustomerContacted");
		}
	}
	
	/// <summary>
	/// Select the customer account or contact to provide a quick link to additional customer details, such as account information, activities, and opportunities.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customerid")]
	public Microsoft.Xrm.Sdk.EntityReference CustomerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("customerid");
		}
		set
		{
			this.OnPropertyChanging("CustomerId");
			this.SetAttributeValue("customerid", value);
			this.OnPropertyChanged("CustomerId");
		}
	}
	
	/// <summary>
	/// Select the customer's level of satisfaction with the handling and resolution of the case.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customersatisfactioncode")]
	public virtual incident_customersatisfactioncode? CustomerSatisfactionCode
	{
		get
		{
			return ((incident_customersatisfactioncode?)(EntityOptionSetEnum.GetEnum(this, "customersatisfactioncode")));
		}
		set
		{
			this.OnPropertyChanging("CustomerSatisfactionCode");
			this.SetAttributeValue("customersatisfactioncode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("CustomerSatisfactionCode");
		}
	}
	
	/// <summary>
	/// Shows the date time when the Case was resolved.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("deactivatedon")]
	public System.Nullable<System.DateTime> deactivatedon
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("deactivatedon");
		}
		set
		{
			this.OnPropertyChanging("deactivatedon");
			this.SetAttributeValue("deactivatedon", value);
			this.OnPropertyChanged("deactivatedon");
		}
	}
	
	/// <summary>
	/// Shows whether terms of the associated entitlement should be decremented or not.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("decremententitlementterm")]
	public System.Nullable<bool> DecrementEntitlementTerm
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("decremententitlementterm");
		}
		set
		{
			this.OnPropertyChanging("DecrementEntitlementTerm");
			this.SetAttributeValue("decremententitlementterm", value);
			this.OnPropertyChanged("DecrementEntitlementTerm");
		}
	}
	
	/// <summary>
	/// Type additional information to describe the case to assist the service team in reaching a resolution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
	public string Description
	{
		get
		{
			return this.GetAttributeValue<string>("description");
		}
		set
		{
			this.OnPropertyChanging("Description");
			this.SetAttributeValue("description", value);
			this.OnPropertyChanged("Description");
		}
	}
	
	/// <summary>
	/// The primary email address for the entity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailaddress")]
	public string EmailAddress
	{
		get
		{
			return this.GetAttributeValue<string>("emailaddress");
		}
		set
		{
			this.OnPropertyChanging("EmailAddress");
			this.SetAttributeValue("emailaddress", value);
			this.OnPropertyChanged("EmailAddress");
		}
	}
	
	/// <summary>
	/// Choose the entitlement that is applicable for the case.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entitlementid")]
	public Microsoft.Xrm.Sdk.EntityReference EntitlementId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("entitlementid");
		}
		set
		{
			this.OnPropertyChanging("EntitlementId");
			this.SetAttributeValue("entitlementid", value);
			this.OnPropertyChanged("EntitlementId");
		}
	}
	
	/// <summary>
	/// The default image for the entity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage")]
	public byte[] EntityImage
	{
		get
		{
			return this.GetAttributeValue<byte[]>("entityimage");
		}
		set
		{
			this.OnPropertyChanging("EntityImage");
			this.SetAttributeValue("entityimage", value);
			this.OnPropertyChanged("EntityImage");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_timestamp")]
	public System.Nullable<long> EntityImage_Timestamp
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("entityimage_timestamp");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_url")]
	public string EntityImage_URL
	{
		get
		{
			return this.GetAttributeValue<string>("entityimage_url");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimageid")]
	public System.Nullable<System.Guid> EntityImageId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("entityimageid");
		}
	}
	
	/// <summary>
	/// Indicates the date and time when the case was escalated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("escalatedon")]
	public System.Nullable<System.DateTime> EscalatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("escalatedon");
		}
	}
	
	/// <summary>
	/// Shows the conversion rate of the record's currency. The exchange rate is used to convert all money fields in the record from the local currency to the system's default currency.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
	public System.Nullable<decimal> ExchangeRate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
		}
	}
	
	/// <summary>
	/// Select an existing case for the customer that has been populated. For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("existingcase")]
	public Microsoft.Xrm.Sdk.EntityReference ExistingCase
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("existingcase");
		}
		set
		{
			this.OnPropertyChanging("ExistingCase");
			this.SetAttributeValue("existingcase", value);
			this.OnPropertyChanged("ExistingCase");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("firstresponsebykpiid")]
	public Microsoft.Xrm.Sdk.EntityReference FirstResponseByKPIId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("firstresponsebykpiid");
		}
		set
		{
			this.OnPropertyChanging("FirstResponseByKPIId");
			this.SetAttributeValue("firstresponsebykpiid", value);
			this.OnPropertyChanged("FirstResponseByKPIId");
		}
	}
	
	/// <summary>
	/// Indicates if the first response has been sent.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("firstresponsesent")]
	public System.Nullable<bool> FirstResponseSent
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("firstresponsesent");
		}
		set
		{
			this.OnPropertyChanging("FirstResponseSent");
			this.SetAttributeValue("firstresponsesent", value);
			this.OnPropertyChanged("FirstResponseSent");
		}
	}
	
	/// <summary>
	/// Shows the status of the initial response time for the case according to the terms of the SLA.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("firstresponseslastatus")]
	public virtual incident_firstresponseslastatus? FirstResponseSLAStatus
	{
		get
		{
			return ((incident_firstresponseslastatus?)(EntityOptionSetEnum.GetEnum(this, "firstresponseslastatus")));
		}
		set
		{
			this.OnPropertyChanging("FirstResponseSLAStatus");
			this.SetAttributeValue("firstresponseslastatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("FirstResponseSLAStatus");
		}
	}
	
	/// <summary>
	/// Enter the date by which a customer service representative has to follow up with the customer on this case.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("followupby")]
	public System.Nullable<System.DateTime> FollowupBy
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("followupby");
		}
		set
		{
			this.OnPropertyChanging("FollowupBy");
			this.SetAttributeValue("followupby", value);
			this.OnPropertyChanged("FollowupBy");
		}
	}
	
	/// <summary>
	/// This attribute is used for Sample Service Business Processes.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("followuptaskcreated")]
	public System.Nullable<bool> FollowUpTaskCreated
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("followuptaskcreated");
		}
		set
		{
			this.OnPropertyChanging("FollowUpTaskCreated");
			this.SetAttributeValue("followuptaskcreated", value);
			this.OnPropertyChanged("FollowUpTaskCreated");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the case.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("incidentid")]
	public System.Nullable<System.Guid> IncidentId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("incidentid");
		}
		set
		{
			this.OnPropertyChanging("IncidentId");
			this.SetAttributeValue("incidentid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("IncidentId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("incidentid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.IncidentId = value;
		}
	}
	
	/// <summary>
	/// Select the current stage of the service process for the case to assist service team members when they review or transfer a case.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("incidentstagecode")]
	public virtual incident_incidentstagecode? IncidentStageCode
	{
		get
		{
			return ((incident_incidentstagecode?)(EntityOptionSetEnum.GetEnum(this, "incidentstagecode")));
		}
		set
		{
			this.OnPropertyChanging("IncidentStageCode");
			this.SetAttributeValue("incidentstagecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("IncidentStageCode");
		}
	}
	
	/// <summary>
	/// Will contain the Influencer score coming from NetBreeze.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("influencescore")]
	public System.Nullable<double> InfluenceScore
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<double>>("influencescore");
		}
		set
		{
			this.OnPropertyChanging("InfluenceScore");
			this.SetAttributeValue("influencescore", value);
			this.OnPropertyChanged("InfluenceScore");
		}
	}
	
	/// <summary>
	/// For system use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isdecrementing")]
	public System.Nullable<bool> IsDecrementing
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("isdecrementing");
		}
		set
		{
			this.OnPropertyChanging("IsDecrementing");
			this.SetAttributeValue("isdecrementing", value);
			this.OnPropertyChanged("IsDecrementing");
		}
	}
	
	/// <summary>
	/// Indicates if the case has been escalated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isescalated")]
	public System.Nullable<bool> IsEscalated
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("isescalated");
		}
		set
		{
			this.OnPropertyChanging("IsEscalated");
			this.SetAttributeValue("isescalated", value);
			this.OnPropertyChanged("IsEscalated");
		}
	}
	
	/// <summary>
	/// Choose the article that contains additional information or a resolution for the case, for reference during research or follow up with the customer.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("kbarticleid")]
	public Microsoft.Xrm.Sdk.EntityReference KbArticleId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("kbarticleid");
		}
		set
		{
			this.OnPropertyChanging("KbArticleId");
			this.SetAttributeValue("kbarticleid", value);
			this.OnPropertyChanged("KbArticleId");
		}
	}
	
	/// <summary>
	/// Shows the latest activity associated with the Case and the action performed on that activity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lastinteraction")]
	public string lastinteraction
	{
		get
		{
			return this.GetAttributeValue<string>("lastinteraction");
		}
	}
	
	/// <summary>
	/// Contains the date time stamp of the last on hold time.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lastonholdtime")]
	public System.Nullable<System.DateTime> LastOnHoldTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("lastonholdtime");
		}
		set
		{
			this.OnPropertyChanging("LastOnHoldTime");
			this.SetAttributeValue("lastonholdtime", value);
			this.OnPropertyChanged("LastOnHoldTime");
		}
	}
	
	/// <summary>
	/// Choose the primary case the current case was merged into.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("masterid")]
	public Microsoft.Xrm.Sdk.EntityReference MasterId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("masterid");
		}
		set
		{
			this.OnPropertyChanging("MasterId");
			this.SetAttributeValue("masterid", value);
			this.OnPropertyChanged("MasterId");
		}
	}
	
	/// <summary>
	/// Tells whether the incident has been merged with another incident.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("merged")]
	public System.Nullable<bool> Merged
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("merged");
		}
	}
	
	/// <summary>
	/// Shows whether the post originated as a public or private message.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("messagetypecode")]
	public virtual socialactivity_postmessagetype? MessageTypeCode
	{
		get
		{
			return ((socialactivity_postmessagetype?)(EntityOptionSetEnum.GetEnum(this, "messagetypecode")));
		}
		set
		{
			this.OnPropertyChanging("MessageTypeCode");
			this.SetAttributeValue("messagetypecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("MessageTypeCode");
		}
	}
	
	/// <summary>
	/// Shows who last updated the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Shows the external party who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyexternalparty")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedByExternalParty
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedbyexternalparty");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Shows who last updated the record on behalf of another user.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// Status of AI Agent for the given record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_aiagentstatus")]
	public Microsoft.Xrm.Sdk.EntityReference msdyn_aiagentstatus
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_aiagentstatus");
		}
		set
		{
			this.OnPropertyChanging("msdyn_aiagentstatus");
			this.SetAttributeValue("msdyn_aiagentstatus", value);
			this.OnPropertyChanged("msdyn_aiagentstatus");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_casesentiment")]
	public virtual msdyn_case_msdyn_casesentiment? msdyn_casesentiment
	{
		get
		{
			return ((msdyn_case_msdyn_casesentiment?)(EntityOptionSetEnum.GetEnum(this, "msdyn_casesentiment")));
		}
		set
		{
			this.OnPropertyChanging("msdyn_casesentiment");
			this.SetAttributeValue("msdyn_casesentiment", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("msdyn_casesentiment");
		}
	}
	
	/// <summary>
	/// Survey invite url for customer feedback.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_casesurveyinviteurl")]
	public string msdyn_CaseSurveyInviteUrl
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_casesurveyinviteurl");
		}
		set
		{
			this.OnPropertyChanging("msdyn_CaseSurveyInviteUrl");
			this.SetAttributeValue("msdyn_casesurveyinviteurl", value);
			this.OnPropertyChanged("msdyn_CaseSurveyInviteUrl");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_copilotengaged")]
	public System.Nullable<bool> msdyn_copilotengaged
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("msdyn_copilotengaged");
		}
		set
		{
			this.OnPropertyChanging("msdyn_copilotengaged");
			this.SetAttributeValue("msdyn_copilotengaged", value);
			this.OnPropertyChanged("msdyn_copilotengaged");
		}
	}
	
	/// <summary>
	/// Case's functional location
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_functionallocation")]
	public Microsoft.Xrm.Sdk.EntityReference msdyn_FunctionalLocation
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_functionallocation");
		}
		set
		{
			this.OnPropertyChanging("msdyn_FunctionalLocation");
			this.SetAttributeValue("msdyn_functionallocation", value);
			this.OnPropertyChanged("msdyn_FunctionalLocation");
		}
	}
	
	/// <summary>
	/// Unique identifier for Incident Type associated with Case.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_incidenttype")]
	public Microsoft.Xrm.Sdk.EntityReference msdyn_IncidentType
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_incidenttype");
		}
		set
		{
			this.OnPropertyChanging("msdyn_IncidentType");
			this.SetAttributeValue("msdyn_incidenttype", value);
			this.OnPropertyChanged("msdyn_IncidentType");
		}
	}
	
	/// <summary>
	/// The iot alert that initiated this case
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_iotalert")]
	public Microsoft.Xrm.Sdk.EntityReference msdyn_iotalert
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_iotalert");
		}
		set
		{
			this.OnPropertyChanging("msdyn_iotalert");
			this.SetAttributeValue("msdyn_iotalert", value);
			this.OnPropertyChanged("msdyn_iotalert");
		}
	}
	
	/// <summary>
	/// Entity Attachments Id before the case record is created
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_precreateattachmentsid")]
	public string msdyn_precreateattachmentsid
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_precreateattachmentsid");
		}
		set
		{
			this.OnPropertyChanging("msdyn_precreateattachmentsid");
			this.SetAttributeValue("msdyn_precreateattachmentsid", value);
			this.OnPropertyChanged("msdyn_precreateattachmentsid");
		}
	}
	
	/// <summary>
	/// Notes Id before the case record is created
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_precreatenotesid")]
	public string msdyn_precreatenotesid
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_precreatenotesid");
		}
		set
		{
			this.OnPropertyChanging("msdyn_precreatenotesid");
			this.SetAttributeValue("msdyn_precreatenotesid", value);
			this.OnPropertyChanged("msdyn_precreatenotesid");
		}
	}
	
	/// <summary>
	/// Shows the unresolved SLA KPI associated with the Case with the earliest expiry time.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nextsla")]
	public string nextsla
	{
		get
		{
			return this.GetAttributeValue<string>("nextsla");
		}
		set
		{
			this.OnPropertyChanging("nextsla");
			this.SetAttributeValue("nextsla", value);
			this.OnPropertyChanged("nextsla");
		}
	}
	
	/// <summary>
	/// Number of child incidents associated with the incident.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("numberofchildincidents")]
	public System.Nullable<int> NumberOfChildIncidents
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("numberofchildincidents");
		}
	}
	
	/// <summary>
	/// Shows the duration in minutes for which the case was on hold.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("onholdtime")]
	public System.Nullable<int> OnHoldTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("onholdtime");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
		set
		{
			this.OnPropertyChanging("OwningBusinessUnit");
			this.SetAttributeValue("owningbusinessunit", value);
			this.OnPropertyChanged("OwningBusinessUnit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Choose the parent case for a case.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentcaseid")]
	public Microsoft.Xrm.Sdk.EntityReference ParentCaseId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("parentcaseid");
		}
		set
		{
			this.OnPropertyChanging("ParentCaseId");
			this.SetAttributeValue("parentcaseid", value);
			this.OnPropertyChanged("ParentCaseId");
		}
	}
	
	/// <summary>
	/// Select a primary contact for this case.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("primarycontactid")]
	public Microsoft.Xrm.Sdk.EntityReference PrimaryContactId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("primarycontactid");
		}
		set
		{
			this.OnPropertyChanging("PrimaryContactId");
			this.SetAttributeValue("primarycontactid", value);
			this.OnPropertyChanged("PrimaryContactId");
		}
	}
	
	/// <summary>
	/// Select the priority so that preferred customers or critical issues are handled quickly.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("prioritycode")]
	public virtual incident_prioritycode? PriorityCode
	{
		get
		{
			return ((incident_prioritycode?)(EntityOptionSetEnum.GetEnum(this, "prioritycode")));
		}
		set
		{
			this.OnPropertyChanging("PriorityCode");
			this.SetAttributeValue("prioritycode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("PriorityCode");
		}
	}
	
	/// <summary>
	/// Contains the id of the process associated with the entity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
	public System.Nullable<System.Guid> ProcessId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
		}
		set
		{
			this.OnPropertyChanging("ProcessId");
			this.SetAttributeValue("processid", value);
			this.OnPropertyChanged("ProcessId");
		}
	}
	
	/// <summary>
	/// Choose the product associated with the case to identify warranty, service, or other product issues and be able to report the number of incidents for each product.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("productid")]
	public Microsoft.Xrm.Sdk.EntityReference ProductId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("productid");
		}
		set
		{
			this.OnPropertyChanging("ProductId");
			this.SetAttributeValue("productid", value);
			this.OnPropertyChanged("ProductId");
		}
	}
	
	/// <summary>
	/// Type the serial number of the product that is associated with this case, so that the number of cases per product can be reported.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("productserialnumber")]
	public string ProductSerialNumber
	{
		get
		{
			return this.GetAttributeValue<string>("productserialnumber");
		}
		set
		{
			this.OnPropertyChanging("ProductSerialNumber");
			this.SetAttributeValue("productserialnumber", value);
			this.OnPropertyChanged("ProductSerialNumber");
		}
	}
	
	/// <summary>
	/// Enter the date by when the case must be resolved.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("resolveby")]
	public System.Nullable<System.DateTime> ResolveBy
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("resolveby");
		}
		set
		{
			this.OnPropertyChanging("ResolveBy");
			this.SetAttributeValue("resolveby", value);
			this.OnPropertyChanged("ResolveBy");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("resolvebykpiid")]
	public Microsoft.Xrm.Sdk.EntityReference ResolveByKPIId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("resolvebykpiid");
		}
		set
		{
			this.OnPropertyChanging("ResolveByKPIId");
			this.SetAttributeValue("resolvebykpiid", value);
			this.OnPropertyChanged("ResolveByKPIId");
		}
	}
	
	/// <summary>
	/// Shows the status of the resolution time for the case according to the terms of the SLA.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("resolvebyslastatus")]
	public virtual incident_resolvebyslastatus? ResolveBySLAStatus
	{
		get
		{
			return ((incident_resolvebyslastatus?)(EntityOptionSetEnum.GetEnum(this, "resolvebyslastatus")));
		}
		set
		{
			this.OnPropertyChanging("ResolveBySLAStatus");
			this.SetAttributeValue("resolvebyslastatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("ResolveBySLAStatus");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("responseby")]
	public System.Nullable<System.DateTime> ResponseBy
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("responseby");
		}
		set
		{
			this.OnPropertyChanging("ResponseBy");
			this.SetAttributeValue("responseby", value);
			this.OnPropertyChanged("ResponseBy");
		}
	}
	
	/// <summary>
	/// Choose an additional customer contact who can also help resolve the case.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("responsiblecontactid")]
	[System.ObsoleteAttribute()]
	public Microsoft.Xrm.Sdk.EntityReference ResponsibleContactId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("responsiblecontactid");
		}
		set
		{
			this.OnPropertyChanging("ResponsibleContactId");
			this.SetAttributeValue("responsiblecontactid", value);
			this.OnPropertyChanged("ResponsibleContactId");
		}
	}
	
	/// <summary>
	/// Tells whether the incident has been routed to queue or not.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("routecase")]
	public System.Nullable<bool> RouteCase
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("routecase");
		}
		set
		{
			this.OnPropertyChanging("RouteCase");
			this.SetAttributeValue("routecase", value);
			this.OnPropertyChanged("RouteCase");
		}
	}
	
	/// <summary>
	/// Value derived after assessing words commonly associated with a negative, neutral, or positive sentiment that occurs in a social post. Sentiment information can also be reported as numeric values.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sentimentvalue")]
	public System.Nullable<double> SentimentValue
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<double>>("sentimentvalue");
		}
		set
		{
			this.OnPropertyChanging("SentimentValue");
			this.SetAttributeValue("sentimentvalue", value);
			this.OnPropertyChanged("SentimentValue");
		}
	}
	
	/// <summary>
	/// Select the stage, in the case resolution process, that the case is in.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("servicestage")]
	public virtual servicestage? ServiceStage
	{
		get
		{
			return ((servicestage?)(EntityOptionSetEnum.GetEnum(this, "servicestage")));
		}
		set
		{
			this.OnPropertyChanging("ServiceStage");
			this.SetAttributeValue("servicestage", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("ServiceStage");
		}
	}
	
	/// <summary>
	/// Select the severity of this case to indicate the incident's impact on the customer's business.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("severitycode")]
	public virtual incident_severitycode? SeverityCode
	{
		get
		{
			return ((incident_severitycode?)(EntityOptionSetEnum.GetEnum(this, "severitycode")));
		}
		set
		{
			this.OnPropertyChanging("SeverityCode");
			this.SetAttributeValue("severitycode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("SeverityCode");
		}
	}
	
	/// <summary>
	/// Choose the service level agreement (SLA) that you want to apply to the case record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slaid")]
	public Microsoft.Xrm.Sdk.EntityReference SLAId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("slaid");
		}
		set
		{
			this.OnPropertyChanging("SLAId");
			this.SetAttributeValue("slaid", value);
			this.OnPropertyChanged("SLAId");
		}
	}
	
	/// <summary>
	/// Last SLA that was applied to this case. This field is for internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slainvokedid")]
	public Microsoft.Xrm.Sdk.EntityReference SLAInvokedId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("slainvokedid");
		}
	}
	
	/// <summary>
	/// Unique identifier of the social profile with which the case is associated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("socialprofileid")]
	public Microsoft.Xrm.Sdk.EntityReference SocialProfileId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("socialprofileid");
		}
		set
		{
			this.OnPropertyChanging("SocialProfileId");
			this.SetAttributeValue("socialprofileid", value);
			this.OnPropertyChanged("SocialProfileId");
		}
	}
	
	/// <summary>
	/// Contains the id of the stage where the entity is located.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
	public System.Nullable<System.Guid> StageId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
		}
		set
		{
			this.OnPropertyChanging("StageId");
			this.SetAttributeValue("stageid", value);
			this.OnPropertyChanged("StageId");
		}
	}
	
	/// <summary>
	/// Shows whether the case is active, resolved, or canceled. Resolved and canceled cases are read-only and can't be edited unless they are reactivated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual incident_statecode? StateCode
	{
		get
		{
			return ((incident_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("StateCode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("StateCode");
		}
	}
	
	/// <summary>
	/// Select the case's status.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual incident_statuscode? StatusCode
	{
		get
		{
			return ((incident_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("StatusCode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("StatusCode");
		}
	}
	
	/// <summary>
	/// Choose the subject for the case, such as catalog request or product complaint, so customer service managers can identify frequent requests or problem areas. Administrators can configure subjects under Business Management in the Settings area.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("subjectid")]
	public Microsoft.Xrm.Sdk.EntityReference SubjectId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("subjectid");
		}
		set
		{
			this.OnPropertyChanging("SubjectId");
			this.SetAttributeValue("subjectid", value);
			this.OnPropertyChanged("SubjectId");
		}
	}
	
	/// <summary>
	/// Shows the case number for customer reference and searching capabilities. This cannot be modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ticketnumber")]
	public string TicketNumber
	{
		get
		{
			return this.GetAttributeValue<string>("ticketnumber");
		}
		set
		{
			this.OnPropertyChanging("TicketNumber");
			this.SetAttributeValue("ticketnumber", value);
			this.OnPropertyChanged("TicketNumber");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Type a subject or descriptive name, such as the request, issue, or company name, to identify the case in Microsoft Dynamics 365 views.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("title")]
	public string Title
	{
		get
		{
			return this.GetAttributeValue<string>("title");
		}
		set
		{
			this.OnPropertyChanging("Title");
			this.SetAttributeValue("title", value);
			this.OnPropertyChanged("Title");
		}
	}
	
	/// <summary>
	/// Choose the local currency for the record to make sure budgets are reported in the correct currency.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
	public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
		}
		set
		{
			this.OnPropertyChanging("TransactionCurrencyId");
			this.SetAttributeValue("transactioncurrencyid", value);
			this.OnPropertyChanged("TransactionCurrencyId");
		}
	}
	
	/// <summary>
	/// A comma separated list of string values representing the unique identifiers of stages in a Business Process Flow Instance in the order that they occur.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
	public string TraversedPath
	{
		get
		{
			return this.GetAttributeValue<string>("traversedpath");
		}
		set
		{
			this.OnPropertyChanging("TraversedPath");
			this.SetAttributeValue("traversedpath", value);
			this.OnPropertyChanged("TraversedPath");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N incident_existingcase
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("incident_existingcase", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
	public System.Collections.Generic.IEnumerable<Incident> Referencedincident_existingcase
	{
		get
		{
			return this.GetRelatedEntities<Incident>("incident_existingcase", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		}
		set
		{
			this.OnPropertyChanging("Referencedincident_existingcase");
			this.SetRelatedEntities<Incident>("incident_existingcase", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			this.OnPropertyChanged("Referencedincident_existingcase");
		}
	}
	
	/// <summary>
	/// 1:N incident_master_incident
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("incident_master_incident", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
	public System.Collections.Generic.IEnumerable<Incident> Referencedincident_master_incident
	{
		get
		{
			return this.GetRelatedEntities<Incident>("incident_master_incident", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		}
		set
		{
			this.OnPropertyChanging("Referencedincident_master_incident");
			this.SetRelatedEntities<Incident>("incident_master_incident", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			this.OnPropertyChanged("Referencedincident_master_incident");
		}
	}
	
	/// <summary>
	/// 1:N incident_parent_incident
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("incident_parent_incident", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
	public System.Collections.Generic.IEnumerable<Incident> Referencedincident_parent_incident
	{
		get
		{
			return this.GetRelatedEntities<Incident>("incident_parent_incident", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		}
		set
		{
			this.OnPropertyChanging("Referencedincident_parent_incident");
			this.SetRelatedEntities<Incident>("incident_parent_incident", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			this.OnPropertyChanged("Referencedincident_parent_incident");
		}
	}
	
	/// <summary>
	/// N:N bshcs_incident_bshcs_billingfunctionallocation
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bshcs_incident_bshcs_billingfunctionallocation")]
	public System.Collections.Generic.IEnumerable<bshcs_billingFunctionalLocation> bshcs_incident_bshcs_billingfunctionallocation
	{
		get
		{
			return this.GetRelatedEntities<bshcs_billingFunctionalLocation>("bshcs_incident_bshcs_billingfunctionallocation", null);
		}
		set
		{
			this.OnPropertyChanging("bshcs_incident_bshcs_billingfunctionallocation");
			this.SetRelatedEntities<bshcs_billingFunctionalLocation>("bshcs_incident_bshcs_billingfunctionallocation", null, value);
			this.OnPropertyChanged("bshcs_incident_bshcs_billingfunctionallocation");
		}
	}
	
	/// <summary>
	/// N:1 incident_existingcase
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("existingcase")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("incident_existingcase", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
	public Incident Referencingincident_existingcase
	{
		get
		{
			return this.GetRelatedEntity<Incident>("incident_existingcase", Microsoft.Xrm.Sdk.EntityRole.Referencing);
		}
		set
		{
			this.OnPropertyChanging("Referencingincident_existingcase");
			this.SetRelatedEntity<Incident>("incident_existingcase", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			this.OnPropertyChanged("Referencingincident_existingcase");
		}
	}
	
	/// <summary>
	/// N:1 incident_master_incident
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("masterid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("incident_master_incident", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
	public Incident Referencingincident_master_incident
	{
		get
		{
			return this.GetRelatedEntity<Incident>("incident_master_incident", Microsoft.Xrm.Sdk.EntityRole.Referencing);
		}
		set
		{
			this.OnPropertyChanging("Referencingincident_master_incident");
			this.SetRelatedEntity<Incident>("incident_master_incident", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			this.OnPropertyChanged("Referencingincident_master_incident");
		}
	}
	
	/// <summary>
	/// N:1 incident_parent_incident
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentcaseid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("incident_parent_incident", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
	public Incident Referencingincident_parent_incident
	{
		get
		{
			return this.GetRelatedEntity<Incident>("incident_parent_incident", Microsoft.Xrm.Sdk.EntityRole.Referencing);
		}
		set
		{
			this.OnPropertyChanging("Referencingincident_parent_incident");
			this.SetRelatedEntity<Incident>("incident_parent_incident", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			this.OnPropertyChanged("Referencingincident_parent_incident");
		}
	}
}
#pragma warning restore CS1591
