#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum bshcs_partnerfunction
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Billto = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Soldto = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Payer = 2,
}
#pragma warning restore CS1591
