#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the Billing Functional Location
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum bshcs_billingfunctionallocation_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the Billing Functional Location
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum bshcs_billingfunctionallocation_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bshcs_billingfunctionallocation")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class bshcs_billingFunctionalLocation : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
		/// <summary>
		/// Available fields, a the time of codegen, for the bshcs_billingfunctionallocation entity
		/// </summary>
		public partial class Fields
		{
			public const string bshcs_accountid = "bshcs_accountid";
			public const string bshcs_billingFunctionalLocationId = "bshcs_billingfunctionallocationid";
			public const string Id = "bshcs_billingfunctionallocationid";
			public const string bshcs_functionallocationid = "bshcs_functionallocationid";
			public const string bshcs_name = "bshcs_name";
			public const string bshcs_partnerfunction = "bshcs_partnerfunction";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string bshcs_incident_bshcs_billingfunctionallocation = "bshcs_incident_bshcs_billingfunctionallocation";
			public const string bshcs_billingfunctionallocation_account = "bshcs_billingfunctionallocation_account";
			public const string bshcs_billingfunctionallocation_msdyn_functionallocation = "bshcs_billingfunctionallocation_msdyn_functionallocation";
		}
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public bshcs_billingFunctionalLocation() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "bshcs_billingfunctionallocation";
	
	public const string EntityLogicalCollectionName = "bshcs_billingfunctionallocations";
	
	public const string EntitySetName = "bshcs_billingfunctionallocations";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_accountid")]
	public Microsoft.Xrm.Sdk.EntityReference bshcs_accountid
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bshcs_accountid");
		}
		set
		{
			this.OnPropertyChanging("bshcs_accountid");
			this.SetAttributeValue("bshcs_accountid", value);
			this.OnPropertyChanged("bshcs_accountid");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_billingfunctionallocationid")]
	public System.Nullable<System.Guid> bshcs_billingFunctionalLocationId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("bshcs_billingfunctionallocationid");
		}
		set
		{
			this.OnPropertyChanging("bshcs_billingFunctionalLocationId");
			this.SetAttributeValue("bshcs_billingfunctionallocationid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("bshcs_billingFunctionalLocationId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_billingfunctionallocationid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.bshcs_billingFunctionalLocationId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_functionallocationid")]
	public Microsoft.Xrm.Sdk.EntityReference bshcs_functionallocationid
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bshcs_functionallocationid");
		}
		set
		{
			this.OnPropertyChanging("bshcs_functionallocationid");
			this.SetAttributeValue("bshcs_functionallocationid", value);
			this.OnPropertyChanged("bshcs_functionallocationid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_name")]
	public string bshcs_name
	{
		get
		{
			return this.GetAttributeValue<string>("bshcs_name");
		}
		set
		{
			this.OnPropertyChanging("bshcs_name");
			this.SetAttributeValue("bshcs_name", value);
			this.OnPropertyChanged("bshcs_name");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_partnerfunction")]
	public virtual bshcs_partnerfunction? bshcs_partnerfunction
	{
		get
		{
			return ((bshcs_partnerfunction?)(EntityOptionSetEnum.GetEnum(this, "bshcs_partnerfunction")));
		}
		set
		{
			this.OnPropertyChanging("bshcs_partnerfunction");
			this.SetAttributeValue("bshcs_partnerfunction", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("bshcs_partnerfunction");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
		set
		{
			this.OnPropertyChanging("OwningBusinessUnit");
			this.SetAttributeValue("owningbusinessunit", value);
			this.OnPropertyChanged("OwningBusinessUnit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Status of the Billing Functional Location
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual bshcs_billingfunctionallocation_statecode? statecode
	{
		get
		{
			return ((bshcs_billingfunctionallocation_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the Billing Functional Location
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual bshcs_billingfunctionallocation_statuscode? statuscode
	{
		get
		{
			return ((bshcs_billingfunctionallocation_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// N:N bshcs_incident_bshcs_billingfunctionallocation
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bshcs_incident_bshcs_billingfunctionallocation")]
	public System.Collections.Generic.IEnumerable<Incident> bshcs_incident_bshcs_billingfunctionallocation
	{
		get
		{
			return this.GetRelatedEntities<Incident>("bshcs_incident_bshcs_billingfunctionallocation", null);
		}
		set
		{
			this.OnPropertyChanging("bshcs_incident_bshcs_billingfunctionallocation");
			this.SetRelatedEntities<Incident>("bshcs_incident_bshcs_billingfunctionallocation", null, value);
			this.OnPropertyChanged("bshcs_incident_bshcs_billingfunctionallocation");
		}
	}
	
	/// <summary>
	/// N:1 bshcs_billingfunctionallocation_account
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_accountid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bshcs_billingfunctionallocation_account")]
	public Account bshcs_billingfunctionallocation_account
	{
		get
		{
			return this.GetRelatedEntity<Account>("bshcs_billingfunctionallocation_account", null);
		}
		set
		{
			this.OnPropertyChanging("bshcs_billingfunctionallocation_account");
			this.SetRelatedEntity<Account>("bshcs_billingfunctionallocation_account", null, value);
			this.OnPropertyChanged("bshcs_billingfunctionallocation_account");
		}
	}
	
	/// <summary>
	/// N:1 bshcs_billingfunctionallocation_msdyn_functionallocation
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_functionallocationid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bshcs_billingfunctionallocation_msdyn_functionallocation")]
	public msdyn_FunctionalLocation bshcs_billingfunctionallocation_msdyn_functionallocation
	{
		get
		{
			return this.GetRelatedEntity<msdyn_FunctionalLocation>("bshcs_billingfunctionallocation_msdyn_functionallocation", null);
		}
		set
		{
			this.OnPropertyChanging("bshcs_billingfunctionallocation_msdyn_functionallocation");
			this.SetRelatedEntity<msdyn_FunctionalLocation>("bshcs_billingfunctionallocation_msdyn_functionallocation", null, value);
			this.OnPropertyChanged("bshcs_billingfunctionallocation_msdyn_functionallocation");
		}
	}
}
#pragma warning restore CS1591
