#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the Functional Location
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum msdyn_functionallocation_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the Functional Location
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum msdyn_functionallocation_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msdyn_functionallocation")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class msdyn_FunctionalLocation : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
		/// <summary>
		/// Available fields, a the time of codegen, for the msdyn_functionallocation entity
		/// </summary>
		public partial class Fields
		{
			public const string bshcs_accountid = "bshcs_accountid";
			public const string bshcs_addresscomposite = "bshcs_addresscomposite";
			public const string bshcs_flatapartment = "bshcs_flatapartment";
			public const string bshcs_housenumber = "bshcs_housenumber";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string msdyn_Address1 = "msdyn_address1";
			public const string msdyn_Address2 = "msdyn_address2";
			public const string msdyn_Address3 = "msdyn_address3";
			public const string msdyn_AddressName = "msdyn_addressname";
			public const string msdyn_City = "msdyn_city";
			public const string msdyn_CostCenter = "msdyn_costcenter";
			public const string msdyn_Country = "msdyn_country";
			public const string msdyn_EmailAddress = "msdyn_emailaddress";
			public const string msdyn_FunctionalLocationId = "msdyn_functionallocationid";
			public const string Id = "msdyn_functionallocationid";
			public const string msdyn_FunctionalLocationType = "msdyn_functionallocationtype";
			public const string msdyn_Latitude = "msdyn_latitude";
			public const string msdyn_LocationOpenDate = "msdyn_locationopendate";
			public const string msdyn_Longitude = "msdyn_longitude";
			public const string msdyn_Name = "msdyn_name";
			public const string msdyn_ParentFunctionalLocation = "msdyn_parentfunctionallocation";
			public const string msdyn_PostalCode = "msdyn_postalcode";
			public const string msdyn_PrimaryTimeZone = "msdyn_primarytimezone";
			public const string msdyn_Sequence = "msdyn_sequence";
			public const string msdyn_ShortName = "msdyn_shortname";
			public const string msdyn_StateOrProvince = "msdyn_stateorprovince";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string bshcs_account_mainaddressid_msdyn_functionallocation = "bshcs_account_mainaddressid_msdyn_functionallocation";
			public const string bshcs_billingfunctionallocation_msdyn_functionallocation = "bshcs_billingfunctionallocation_msdyn_functionallocation";
			public const string Referencedmsdyn_FunctionalLocation_ParentFunctional = "Referencedmsdyn_FunctionalLocation_ParentFunctional";
			public const string msdyn_msdyn_functionallocation_incident_FunctionalLocation = "msdyn_msdyn_functionallocation_incident_FunctionalLocation";
			public const string msdyn_msdyn_functionallocation_account = "msdyn_msdyn_functionallocation_account";
			public const string bshcs_account_msdyn_functionallocation = "bshcs_account_msdyn_functionallocation";
			public const string Referencingmsdyn_FunctionalLocation_ParentFunctional = "msdyn_FunctionalLocation_ParentFunctional";
		}
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public msdyn_FunctionalLocation() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "msdyn_functionallocation";
	
	public const string EntityLogicalCollectionName = "msdyn_functionallocations";
	
	public const string EntitySetName = "msdyn_functionallocations";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_accountid")]
	public Microsoft.Xrm.Sdk.EntityReference bshcs_accountid
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bshcs_accountid");
		}
		set
		{
			this.OnPropertyChanging("bshcs_accountid");
			this.SetAttributeValue("bshcs_accountid", value);
			this.OnPropertyChanged("bshcs_accountid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_addresscomposite")]
	public string bshcs_addresscomposite
	{
		get
		{
			return this.GetAttributeValue<string>("bshcs_addresscomposite");
		}
		set
		{
			this.OnPropertyChanging("bshcs_addresscomposite");
			this.SetAttributeValue("bshcs_addresscomposite", value);
			this.OnPropertyChanged("bshcs_addresscomposite");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_flatapartment")]
	public string bshcs_flatapartment
	{
		get
		{
			return this.GetAttributeValue<string>("bshcs_flatapartment");
		}
		set
		{
			this.OnPropertyChanging("bshcs_flatapartment");
			this.SetAttributeValue("bshcs_flatapartment", value);
			this.OnPropertyChanged("bshcs_flatapartment");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_housenumber")]
	public string bshcs_housenumber
	{
		get
		{
			return this.GetAttributeValue<string>("bshcs_housenumber");
		}
		set
		{
			this.OnPropertyChanging("bshcs_housenumber");
			this.SetAttributeValue("bshcs_housenumber", value);
			this.OnPropertyChanged("bshcs_housenumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_address1")]
	public string msdyn_Address1
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_address1");
		}
		set
		{
			this.OnPropertyChanging("msdyn_Address1");
			this.SetAttributeValue("msdyn_address1", value);
			this.OnPropertyChanged("msdyn_Address1");
		}
	}
	
	/// <summary>
	/// Street 2
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_address2")]
	public string msdyn_Address2
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_address2");
		}
		set
		{
			this.OnPropertyChanging("msdyn_Address2");
			this.SetAttributeValue("msdyn_address2", value);
			this.OnPropertyChanged("msdyn_Address2");
		}
	}
	
	/// <summary>
	/// Street 3
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_address3")]
	public string msdyn_Address3
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_address3");
		}
		set
		{
			this.OnPropertyChanging("msdyn_Address3");
			this.SetAttributeValue("msdyn_address3", value);
			this.OnPropertyChanged("msdyn_Address3");
		}
	}
	
	/// <summary>
	/// Address Name
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_addressname")]
	public string msdyn_AddressName
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_addressname");
		}
		set
		{
			this.OnPropertyChanging("msdyn_AddressName");
			this.SetAttributeValue("msdyn_addressname", value);
			this.OnPropertyChanged("msdyn_AddressName");
		}
	}
	
	/// <summary>
	/// City
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_city")]
	public string msdyn_City
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_city");
		}
		set
		{
			this.OnPropertyChanging("msdyn_City");
			this.SetAttributeValue("msdyn_city", value);
			this.OnPropertyChanged("msdyn_City");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_costcenter")]
	public string msdyn_CostCenter
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_costcenter");
		}
		set
		{
			this.OnPropertyChanging("msdyn_CostCenter");
			this.SetAttributeValue("msdyn_costcenter", value);
			this.OnPropertyChanged("msdyn_CostCenter");
		}
	}
	
	/// <summary>
	/// Country/Region
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_country")]
	public string msdyn_Country
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_country");
		}
		set
		{
			this.OnPropertyChanging("msdyn_Country");
			this.SetAttributeValue("msdyn_country", value);
			this.OnPropertyChanged("msdyn_Country");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_emailaddress")]
	public string msdyn_EmailAddress
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_emailaddress");
		}
		set
		{
			this.OnPropertyChanging("msdyn_EmailAddress");
			this.SetAttributeValue("msdyn_emailaddress", value);
			this.OnPropertyChanged("msdyn_EmailAddress");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_functionallocationid")]
	public System.Nullable<System.Guid> msdyn_FunctionalLocationId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_functionallocationid");
		}
		set
		{
			this.OnPropertyChanging("msdyn_FunctionalLocationId");
			this.SetAttributeValue("msdyn_functionallocationid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("msdyn_FunctionalLocationId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_functionallocationid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.msdyn_FunctionalLocationId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_functionallocationtype")]
	public Microsoft.Xrm.Sdk.EntityReference msdyn_FunctionalLocationType
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_functionallocationtype");
		}
		set
		{
			this.OnPropertyChanging("msdyn_FunctionalLocationType");
			this.SetAttributeValue("msdyn_functionallocationtype", value);
			this.OnPropertyChanged("msdyn_FunctionalLocationType");
		}
	}
	
	/// <summary>
	/// Latitude
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_latitude")]
	public System.Nullable<double> msdyn_Latitude
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<double>>("msdyn_latitude");
		}
		set
		{
			this.OnPropertyChanging("msdyn_Latitude");
			this.SetAttributeValue("msdyn_latitude", value);
			this.OnPropertyChanged("msdyn_Latitude");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_locationopendate")]
	public System.Nullable<System.DateTime> msdyn_LocationOpenDate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_locationopendate");
		}
		set
		{
			this.OnPropertyChanging("msdyn_LocationOpenDate");
			this.SetAttributeValue("msdyn_locationopendate", value);
			this.OnPropertyChanged("msdyn_LocationOpenDate");
		}
	}
	
	/// <summary>
	/// Longitude
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_longitude")]
	public System.Nullable<double> msdyn_Longitude
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<double>>("msdyn_longitude");
		}
		set
		{
			this.OnPropertyChanging("msdyn_Longitude");
			this.SetAttributeValue("msdyn_longitude", value);
			this.OnPropertyChanged("msdyn_Longitude");
		}
	}
	
	/// <summary>
	/// Required name field
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_name")]
	public string msdyn_Name
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_name");
		}
		set
		{
			this.OnPropertyChanging("msdyn_Name");
			this.SetAttributeValue("msdyn_name", value);
			this.OnPropertyChanged("msdyn_Name");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_parentfunctionallocation")]
	public Microsoft.Xrm.Sdk.EntityReference msdyn_ParentFunctionalLocation
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_parentfunctionallocation");
		}
		set
		{
			this.OnPropertyChanging("msdyn_ParentFunctionalLocation");
			this.SetAttributeValue("msdyn_parentfunctionallocation", value);
			this.OnPropertyChanged("msdyn_ParentFunctionalLocation");
		}
	}
	
	/// <summary>
	/// Postal Code
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_postalcode")]
	public string msdyn_PostalCode
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_postalcode");
		}
		set
		{
			this.OnPropertyChanging("msdyn_PostalCode");
			this.SetAttributeValue("msdyn_postalcode", value);
			this.OnPropertyChanged("msdyn_PostalCode");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_primarytimezone")]
	public System.Nullable<int> msdyn_PrimaryTimeZone
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("msdyn_primarytimezone");
		}
		set
		{
			this.OnPropertyChanging("msdyn_PrimaryTimeZone");
			this.SetAttributeValue("msdyn_primarytimezone", value);
			this.OnPropertyChanged("msdyn_PrimaryTimeZone");
		}
	}
	
	/// <summary>
	/// Relative order of functional location entity node in hierarchy control
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_sequence")]
	public System.Nullable<int> msdyn_Sequence
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("msdyn_sequence");
		}
		set
		{
			this.OnPropertyChanging("msdyn_Sequence");
			this.SetAttributeValue("msdyn_sequence", value);
			this.OnPropertyChanged("msdyn_Sequence");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_shortname")]
	public string msdyn_ShortName
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_shortname");
		}
		set
		{
			this.OnPropertyChanging("msdyn_ShortName");
			this.SetAttributeValue("msdyn_shortname", value);
			this.OnPropertyChanged("msdyn_ShortName");
		}
	}
	
	/// <summary>
	/// State Or Province
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_stateorprovince")]
	public string msdyn_StateOrProvince
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_stateorprovince");
		}
		set
		{
			this.OnPropertyChanging("msdyn_StateOrProvince");
			this.SetAttributeValue("msdyn_stateorprovince", value);
			this.OnPropertyChanged("msdyn_StateOrProvince");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
		set
		{
			this.OnPropertyChanging("OwningBusinessUnit");
			this.SetAttributeValue("owningbusinessunit", value);
			this.OnPropertyChanged("OwningBusinessUnit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Status of the Functional Location
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual msdyn_functionallocation_statecode? statecode
	{
		get
		{
			return ((msdyn_functionallocation_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the Functional Location
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual msdyn_functionallocation_statuscode? statuscode
	{
		get
		{
			return ((msdyn_functionallocation_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N bshcs_account_mainaddressid_msdyn_functionallocation
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bshcs_account_mainaddressid_msdyn_functionallocation")]
	public System.Collections.Generic.IEnumerable<Account> bshcs_account_mainaddressid_msdyn_functionallocation
	{
		get
		{
			return this.GetRelatedEntities<Account>("bshcs_account_mainaddressid_msdyn_functionallocation", null);
		}
		set
		{
			this.OnPropertyChanging("bshcs_account_mainaddressid_msdyn_functionallocation");
			this.SetRelatedEntities<Account>("bshcs_account_mainaddressid_msdyn_functionallocation", null, value);
			this.OnPropertyChanged("bshcs_account_mainaddressid_msdyn_functionallocation");
		}
	}
	
	/// <summary>
	/// 1:N bshcs_billingfunctionallocation_msdyn_functionallocation
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bshcs_billingfunctionallocation_msdyn_functionallocation")]
	public System.Collections.Generic.IEnumerable<bshcs_billingFunctionalLocation> bshcs_billingfunctionallocation_msdyn_functionallocation
	{
		get
		{
			return this.GetRelatedEntities<bshcs_billingFunctionalLocation>("bshcs_billingfunctionallocation_msdyn_functionallocation", null);
		}
		set
		{
			this.OnPropertyChanging("bshcs_billingfunctionallocation_msdyn_functionallocation");
			this.SetRelatedEntities<bshcs_billingFunctionalLocation>("bshcs_billingfunctionallocation_msdyn_functionallocation", null, value);
			this.OnPropertyChanged("bshcs_billingfunctionallocation_msdyn_functionallocation");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_FunctionalLocation_ParentFunctional
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_FunctionalLocation_ParentFunctional", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
	public System.Collections.Generic.IEnumerable<msdyn_FunctionalLocation> Referencedmsdyn_FunctionalLocation_ParentFunctional
	{
		get
		{
			return this.GetRelatedEntities<msdyn_FunctionalLocation>("msdyn_FunctionalLocation_ParentFunctional", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		}
		set
		{
			this.OnPropertyChanging("Referencedmsdyn_FunctionalLocation_ParentFunctional");
			this.SetRelatedEntities<msdyn_FunctionalLocation>("msdyn_FunctionalLocation_ParentFunctional", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			this.OnPropertyChanged("Referencedmsdyn_FunctionalLocation_ParentFunctional");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_msdyn_functionallocation_incident_FunctionalLocation
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_functionallocation_incident_FunctionalLocation")]
	public System.Collections.Generic.IEnumerable<Incident> msdyn_msdyn_functionallocation_incident_FunctionalLocation
	{
		get
		{
			return this.GetRelatedEntities<Incident>("msdyn_msdyn_functionallocation_incident_FunctionalLocation", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_msdyn_functionallocation_incident_FunctionalLocation");
			this.SetRelatedEntities<Incident>("msdyn_msdyn_functionallocation_incident_FunctionalLocation", null, value);
			this.OnPropertyChanged("msdyn_msdyn_functionallocation_incident_FunctionalLocation");
		}
	}
	
	/// <summary>
	/// N:N msdyn_msdyn_functionallocation_account
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_functionallocation_account")]
	public System.Collections.Generic.IEnumerable<Account> msdyn_msdyn_functionallocation_account
	{
		get
		{
			return this.GetRelatedEntities<Account>("msdyn_msdyn_functionallocation_account", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_msdyn_functionallocation_account");
			this.SetRelatedEntities<Account>("msdyn_msdyn_functionallocation_account", null, value);
			this.OnPropertyChanged("msdyn_msdyn_functionallocation_account");
		}
	}
	
	/// <summary>
	/// N:1 bshcs_account_msdyn_functionallocation
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bshcs_accountid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bshcs_account_msdyn_functionallocation")]
	public Account bshcs_account_msdyn_functionallocation
	{
		get
		{
			return this.GetRelatedEntity<Account>("bshcs_account_msdyn_functionallocation", null);
		}
		set
		{
			this.OnPropertyChanging("bshcs_account_msdyn_functionallocation");
			this.SetRelatedEntity<Account>("bshcs_account_msdyn_functionallocation", null, value);
			this.OnPropertyChanged("bshcs_account_msdyn_functionallocation");
		}
	}
	
	/// <summary>
	/// N:1 msdyn_FunctionalLocation_ParentFunctional
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_parentfunctionallocation")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_FunctionalLocation_ParentFunctional", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
	public msdyn_FunctionalLocation Referencingmsdyn_FunctionalLocation_ParentFunctional
	{
		get
		{
			return this.GetRelatedEntity<msdyn_FunctionalLocation>("msdyn_FunctionalLocation_ParentFunctional", Microsoft.Xrm.Sdk.EntityRole.Referencing);
		}
		set
		{
			this.OnPropertyChanging("Referencingmsdyn_FunctionalLocation_ParentFunctional");
			this.SetRelatedEntity<msdyn_FunctionalLocation>("msdyn_FunctionalLocation_ParentFunctional", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			this.OnPropertyChanged("Referencingmsdyn_FunctionalLocation_ParentFunctional");
		}
	}
}
#pragma warning restore CS1591
